chroot-script: clarify error message iff packages is not available + send it to stderr

diff --git a/chroot-script b/chroot-script
--- a/chroot-script
+++ b/chroot-script
@@ -182,7 +182,7 @@ packages() {
 
   if [ "$PACKAGES" = 'yes' ] ; then
      if ! [ -r /etc/debootstrap/packages ] ; then
-       echo "Error: /etc/debootstrap/packages not found, exiting."
+       echo "Error: /etc/debootstrap/packages (inside chroot) not found, exiting." >&2
        exit 1
      else
        $APTUPDATE
